services:
  - type: web
    name: banking-backend
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: cd backend && gunicorn main:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    plan: free