services:
  - type: web
    name: banking-backend
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT --loop asyncio
    plan: free